// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: glucose.proto

package com.docsinclouds.glucose;

public final class GlucoseProtos {
  private GlucoseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:glucose.SensorValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 value = 1;</code>
     */
    int getValue();

    /**
     * <code>string timestamp = 2;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>string sensor_type = 3;</code>
     */
    java.lang.String getSensorType();
    /**
     * <code>string sensor_type = 3;</code>
     */
    com.google.protobuf.ByteString
        getSensorTypeBytes();
  }
  /**
   * Protobuf type {@code glucose.SensorValue}
   */
  public  static final class SensorValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:glucose.SensorValue)
      SensorValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorValue.newBuilder() to construct.
    private SensorValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorValue() {
      value_ = 0;
      timestamp_ = "";
      sensorType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              value_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sensorType_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_SensorValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_SensorValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.docsinclouds.glucose.GlucoseProtos.SensorValue.class, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>int32 value = 1;</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timestamp_;
    /**
     * <code>string timestamp = 2;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSOR_TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object sensorType_;
    /**
     * <code>string sensor_type = 3;</code>
     */
    public java.lang.String getSensorType() {
      java.lang.Object ref = sensorType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorType_ = s;
        return s;
      }
    }
    /**
     * <code>string sensor_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSensorTypeBytes() {
      java.lang.Object ref = sensorType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0) {
        output.writeInt32(1, value_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timestamp_);
      }
      if (!getSensorTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sensorType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timestamp_);
      }
      if (!getSensorTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sensorType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.docsinclouds.glucose.GlucoseProtos.SensorValue)) {
        return super.equals(obj);
      }
      com.docsinclouds.glucose.GlucoseProtos.SensorValue other = (com.docsinclouds.glucose.GlucoseProtos.SensorValue) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && getSensorType()
          .equals(other.getSensorType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + SENSOR_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSensorType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.docsinclouds.glucose.GlucoseProtos.SensorValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code glucose.SensorValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:glucose.SensorValue)
        com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_SensorValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_SensorValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.docsinclouds.glucose.GlucoseProtos.SensorValue.class, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder.class);
      }

      // Construct using com.docsinclouds.glucose.GlucoseProtos.SensorValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = 0;

        timestamp_ = "";

        sensorType_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_SensorValue_descriptor;
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue getDefaultInstanceForType() {
        return com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue build() {
        com.docsinclouds.glucose.GlucoseProtos.SensorValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue buildPartial() {
        com.docsinclouds.glucose.GlucoseProtos.SensorValue result = new com.docsinclouds.glucose.GlucoseProtos.SensorValue(this);
        result.value_ = value_;
        result.timestamp_ = timestamp_;
        result.sensorType_ = sensorType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.docsinclouds.glucose.GlucoseProtos.SensorValue) {
          return mergeFrom((com.docsinclouds.glucose.GlucoseProtos.SensorValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.docsinclouds.glucose.GlucoseProtos.SensorValue other) {
        if (other == com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getSensorType().isEmpty()) {
          sensorType_ = other.sensorType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.docsinclouds.glucose.GlucoseProtos.SensorValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.docsinclouds.glucose.GlucoseProtos.SensorValue) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int value_ ;
      /**
       * <code>int32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>int32 value = 1;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 2;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 2;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sensorType_ = "";
      /**
       * <code>string sensor_type = 3;</code>
       */
      public java.lang.String getSensorType() {
        java.lang.Object ref = sensorType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sensorType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sensor_type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSensorTypeBytes() {
        java.lang.Object ref = sensorType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensorType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sensor_type = 3;</code>
       */
      public Builder setSensorType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sensorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sensor_type = 3;</code>
       */
      public Builder clearSensorType() {
        
        sensorType_ = getDefaultInstance().getSensorType();
        onChanged();
        return this;
      }
      /**
       * <code>string sensor_type = 3;</code>
       */
      public Builder setSensorTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sensorType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:glucose.SensorValue)
    }

    // @@protoc_insertion_point(class_scope:glucose.SensorValue)
    private static final com.docsinclouds.glucose.GlucoseProtos.SensorValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.docsinclouds.glucose.GlucoseProtos.SensorValue();
    }

    public static com.docsinclouds.glucose.GlucoseProtos.SensorValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorValue>
        PARSER = new com.google.protobuf.AbstractParser<SensorValue>() {
      @java.lang.Override
      public SensorValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorValue(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.docsinclouds.glucose.GlucoseProtos.SensorValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RawValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:glucose.RawValues)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    java.util.List<com.docsinclouds.glucose.GlucoseProtos.SensorValue> 
        getSensorValuesList();
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    com.docsinclouds.glucose.GlucoseProtos.SensorValue getSensorValues(int index);
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    int getSensorValuesCount();
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    java.util.List<? extends com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> 
        getSensorValuesOrBuilderList();
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder getSensorValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code glucose.RawValues}
   */
  public  static final class RawValues extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:glucose.RawValues)
      RawValuesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RawValues.newBuilder() to construct.
    private RawValues(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RawValues() {
      sensorValues_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RawValues(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sensorValues_ = new java.util.ArrayList<com.docsinclouds.glucose.GlucoseProtos.SensorValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              sensorValues_.add(
                  input.readMessage(com.docsinclouds.glucose.GlucoseProtos.SensorValue.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sensorValues_ = java.util.Collections.unmodifiableList(sensorValues_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_RawValues_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_RawValues_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.docsinclouds.glucose.GlucoseProtos.RawValues.class, com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder.class);
    }

    public static final int SENSOR_VALUES_FIELD_NUMBER = 1;
    private java.util.List<com.docsinclouds.glucose.GlucoseProtos.SensorValue> sensorValues_;
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    public java.util.List<com.docsinclouds.glucose.GlucoseProtos.SensorValue> getSensorValuesList() {
      return sensorValues_;
    }
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    public java.util.List<? extends com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> 
        getSensorValuesOrBuilderList() {
      return sensorValues_;
    }
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    public int getSensorValuesCount() {
      return sensorValues_.size();
    }
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    public com.docsinclouds.glucose.GlucoseProtos.SensorValue getSensorValues(int index) {
      return sensorValues_.get(index);
    }
    /**
     * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
     */
    public com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder getSensorValuesOrBuilder(
        int index) {
      return sensorValues_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sensorValues_.size(); i++) {
        output.writeMessage(1, sensorValues_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sensorValues_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sensorValues_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.docsinclouds.glucose.GlucoseProtos.RawValues)) {
        return super.equals(obj);
      }
      com.docsinclouds.glucose.GlucoseProtos.RawValues other = (com.docsinclouds.glucose.GlucoseProtos.RawValues) obj;

      boolean result = true;
      result = result && getSensorValuesList()
          .equals(other.getSensorValuesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSensorValuesCount() > 0) {
        hash = (37 * hash) + SENSOR_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getSensorValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.RawValues parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.docsinclouds.glucose.GlucoseProtos.RawValues prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code glucose.RawValues}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:glucose.RawValues)
        com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_RawValues_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_RawValues_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.docsinclouds.glucose.GlucoseProtos.RawValues.class, com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder.class);
      }

      // Construct using com.docsinclouds.glucose.GlucoseProtos.RawValues.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSensorValuesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (sensorValuesBuilder_ == null) {
          sensorValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sensorValuesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_RawValues_descriptor;
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.RawValues getDefaultInstanceForType() {
        return com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.RawValues build() {
        com.docsinclouds.glucose.GlucoseProtos.RawValues result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.RawValues buildPartial() {
        com.docsinclouds.glucose.GlucoseProtos.RawValues result = new com.docsinclouds.glucose.GlucoseProtos.RawValues(this);
        int from_bitField0_ = bitField0_;
        if (sensorValuesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sensorValues_ = java.util.Collections.unmodifiableList(sensorValues_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sensorValues_ = sensorValues_;
        } else {
          result.sensorValues_ = sensorValuesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.docsinclouds.glucose.GlucoseProtos.RawValues) {
          return mergeFrom((com.docsinclouds.glucose.GlucoseProtos.RawValues)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.docsinclouds.glucose.GlucoseProtos.RawValues other) {
        if (other == com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance()) return this;
        if (sensorValuesBuilder_ == null) {
          if (!other.sensorValues_.isEmpty()) {
            if (sensorValues_.isEmpty()) {
              sensorValues_ = other.sensorValues_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSensorValuesIsMutable();
              sensorValues_.addAll(other.sensorValues_);
            }
            onChanged();
          }
        } else {
          if (!other.sensorValues_.isEmpty()) {
            if (sensorValuesBuilder_.isEmpty()) {
              sensorValuesBuilder_.dispose();
              sensorValuesBuilder_ = null;
              sensorValues_ = other.sensorValues_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sensorValuesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSensorValuesFieldBuilder() : null;
            } else {
              sensorValuesBuilder_.addAllMessages(other.sensorValues_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.docsinclouds.glucose.GlucoseProtos.RawValues parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.docsinclouds.glucose.GlucoseProtos.RawValues) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.docsinclouds.glucose.GlucoseProtos.SensorValue> sensorValues_ =
        java.util.Collections.emptyList();
      private void ensureSensorValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sensorValues_ = new java.util.ArrayList<com.docsinclouds.glucose.GlucoseProtos.SensorValue>(sensorValues_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.docsinclouds.glucose.GlucoseProtos.SensorValue, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder, com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> sensorValuesBuilder_;

      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public java.util.List<com.docsinclouds.glucose.GlucoseProtos.SensorValue> getSensorValuesList() {
        if (sensorValuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sensorValues_);
        } else {
          return sensorValuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public int getSensorValuesCount() {
        if (sensorValuesBuilder_ == null) {
          return sensorValues_.size();
        } else {
          return sensorValuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue getSensorValues(int index) {
        if (sensorValuesBuilder_ == null) {
          return sensorValues_.get(index);
        } else {
          return sensorValuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder setSensorValues(
          int index, com.docsinclouds.glucose.GlucoseProtos.SensorValue value) {
        if (sensorValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorValuesIsMutable();
          sensorValues_.set(index, value);
          onChanged();
        } else {
          sensorValuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder setSensorValues(
          int index, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder builderForValue) {
        if (sensorValuesBuilder_ == null) {
          ensureSensorValuesIsMutable();
          sensorValues_.set(index, builderForValue.build());
          onChanged();
        } else {
          sensorValuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder addSensorValues(com.docsinclouds.glucose.GlucoseProtos.SensorValue value) {
        if (sensorValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorValuesIsMutable();
          sensorValues_.add(value);
          onChanged();
        } else {
          sensorValuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder addSensorValues(
          int index, com.docsinclouds.glucose.GlucoseProtos.SensorValue value) {
        if (sensorValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorValuesIsMutable();
          sensorValues_.add(index, value);
          onChanged();
        } else {
          sensorValuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder addSensorValues(
          com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder builderForValue) {
        if (sensorValuesBuilder_ == null) {
          ensureSensorValuesIsMutable();
          sensorValues_.add(builderForValue.build());
          onChanged();
        } else {
          sensorValuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder addSensorValues(
          int index, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder builderForValue) {
        if (sensorValuesBuilder_ == null) {
          ensureSensorValuesIsMutable();
          sensorValues_.add(index, builderForValue.build());
          onChanged();
        } else {
          sensorValuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder addAllSensorValues(
          java.lang.Iterable<? extends com.docsinclouds.glucose.GlucoseProtos.SensorValue> values) {
        if (sensorValuesBuilder_ == null) {
          ensureSensorValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sensorValues_);
          onChanged();
        } else {
          sensorValuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder clearSensorValues() {
        if (sensorValuesBuilder_ == null) {
          sensorValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sensorValuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public Builder removeSensorValues(int index) {
        if (sensorValuesBuilder_ == null) {
          ensureSensorValuesIsMutable();
          sensorValues_.remove(index);
          onChanged();
        } else {
          sensorValuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder getSensorValuesBuilder(
          int index) {
        return getSensorValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder getSensorValuesOrBuilder(
          int index) {
        if (sensorValuesBuilder_ == null) {
          return sensorValues_.get(index);  } else {
          return sensorValuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public java.util.List<? extends com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> 
           getSensorValuesOrBuilderList() {
        if (sensorValuesBuilder_ != null) {
          return sensorValuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sensorValues_);
        }
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder addSensorValuesBuilder() {
        return getSensorValuesFieldBuilder().addBuilder(
            com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance());
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder addSensorValuesBuilder(
          int index) {
        return getSensorValuesFieldBuilder().addBuilder(
            index, com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance());
      }
      /**
       * <code>repeated .glucose.SensorValue sensor_values = 1;</code>
       */
      public java.util.List<com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder> 
           getSensorValuesBuilderList() {
        return getSensorValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.docsinclouds.glucose.GlucoseProtos.SensorValue, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder, com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> 
          getSensorValuesFieldBuilder() {
        if (sensorValuesBuilder_ == null) {
          sensorValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.docsinclouds.glucose.GlucoseProtos.SensorValue, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder, com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder>(
                  sensorValues_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sensorValues_ = null;
        }
        return sensorValuesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:glucose.RawValues)
    }

    // @@protoc_insertion_point(class_scope:glucose.RawValues)
    private static final com.docsinclouds.glucose.GlucoseProtos.RawValues DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.docsinclouds.glucose.GlucoseProtos.RawValues();
    }

    public static com.docsinclouds.glucose.GlucoseProtos.RawValues getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RawValues>
        PARSER = new com.google.protobuf.AbstractParser<RawValues>() {
      @java.lang.Override
      public RawValues parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RawValues(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RawValues> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RawValues> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.docsinclouds.glucose.GlucoseProtos.RawValues getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:glucose.MetaMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.glucose.SensorValue sensor_value = 1;</code>
     */
    boolean hasSensorValue();
    /**
     * <code>.glucose.SensorValue sensor_value = 1;</code>
     */
    com.docsinclouds.glucose.GlucoseProtos.SensorValue getSensorValue();
    /**
     * <code>.glucose.SensorValue sensor_value = 1;</code>
     */
    com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder getSensorValueOrBuilder();

    /**
     * <code>.glucose.RawValues raw = 2;</code>
     */
    boolean hasRaw();
    /**
     * <code>.glucose.RawValues raw = 2;</code>
     */
    com.docsinclouds.glucose.GlucoseProtos.RawValues getRaw();
    /**
     * <code>.glucose.RawValues raw = 2;</code>
     */
    com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder getRawOrBuilder();

    public com.docsinclouds.glucose.GlucoseProtos.MetaMessage.ContentCase getContentCase();
  }
  /**
   * Protobuf type {@code glucose.MetaMessage}
   */
  public  static final class MetaMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:glucose.MetaMessage)
      MetaMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MetaMessage.newBuilder() to construct.
    private MetaMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetaMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetaMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder subBuilder = null;
              if (contentCase_ == 1) {
                subBuilder = ((com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_).toBuilder();
              }
              content_ =
                  input.readMessage(com.docsinclouds.glucose.GlucoseProtos.SensorValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_);
                content_ = subBuilder.buildPartial();
              }
              contentCase_ = 1;
              break;
            }
            case 18: {
              com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder subBuilder = null;
              if (contentCase_ == 2) {
                subBuilder = ((com.docsinclouds.glucose.GlucoseProtos.RawValues) content_).toBuilder();
              }
              content_ =
                  input.readMessage(com.docsinclouds.glucose.GlucoseProtos.RawValues.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.docsinclouds.glucose.GlucoseProtos.RawValues) content_);
                content_ = subBuilder.buildPartial();
              }
              contentCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_MetaMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_MetaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.docsinclouds.glucose.GlucoseProtos.MetaMessage.class, com.docsinclouds.glucose.GlucoseProtos.MetaMessage.Builder.class);
    }

    private int contentCase_ = 0;
    private java.lang.Object content_;
    public enum ContentCase
        implements com.google.protobuf.Internal.EnumLite {
      SENSOR_VALUE(1),
      RAW(2),
      CONTENT_NOT_SET(0);
      private final int value;
      private ContentCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContentCase forNumber(int value) {
        switch (value) {
          case 1: return SENSOR_VALUE;
          case 2: return RAW;
          case 0: return CONTENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ContentCase
    getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public static final int SENSOR_VALUE_FIELD_NUMBER = 1;
    /**
     * <code>.glucose.SensorValue sensor_value = 1;</code>
     */
    public boolean hasSensorValue() {
      return contentCase_ == 1;
    }
    /**
     * <code>.glucose.SensorValue sensor_value = 1;</code>
     */
    public com.docsinclouds.glucose.GlucoseProtos.SensorValue getSensorValue() {
      if (contentCase_ == 1) {
         return (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_;
      }
      return com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
    }
    /**
     * <code>.glucose.SensorValue sensor_value = 1;</code>
     */
    public com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder getSensorValueOrBuilder() {
      if (contentCase_ == 1) {
         return (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_;
      }
      return com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
    }

    public static final int RAW_FIELD_NUMBER = 2;
    /**
     * <code>.glucose.RawValues raw = 2;</code>
     */
    public boolean hasRaw() {
      return contentCase_ == 2;
    }
    /**
     * <code>.glucose.RawValues raw = 2;</code>
     */
    public com.docsinclouds.glucose.GlucoseProtos.RawValues getRaw() {
      if (contentCase_ == 2) {
         return (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_;
      }
      return com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
    }
    /**
     * <code>.glucose.RawValues raw = 2;</code>
     */
    public com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder getRawOrBuilder() {
      if (contentCase_ == 2) {
         return (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_;
      }
      return com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (contentCase_ == 1) {
        output.writeMessage(1, (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_);
      }
      if (contentCase_ == 2) {
        output.writeMessage(2, (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contentCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_);
      }
      if (contentCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.docsinclouds.glucose.GlucoseProtos.MetaMessage)) {
        return super.equals(obj);
      }
      com.docsinclouds.glucose.GlucoseProtos.MetaMessage other = (com.docsinclouds.glucose.GlucoseProtos.MetaMessage) obj;

      boolean result = true;
      result = result && getContentCase().equals(
          other.getContentCase());
      if (!result) return false;
      switch (contentCase_) {
        case 1:
          result = result && getSensorValue()
              .equals(other.getSensorValue());
          break;
        case 2:
          result = result && getRaw()
              .equals(other.getRaw());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (contentCase_) {
        case 1:
          hash = (37 * hash) + SENSOR_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getSensorValue().hashCode();
          break;
        case 2:
          hash = (37 * hash) + RAW_FIELD_NUMBER;
          hash = (53 * hash) + getRaw().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.docsinclouds.glucose.GlucoseProtos.MetaMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code glucose.MetaMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:glucose.MetaMessage)
        com.docsinclouds.glucose.GlucoseProtos.MetaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_MetaMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_MetaMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.docsinclouds.glucose.GlucoseProtos.MetaMessage.class, com.docsinclouds.glucose.GlucoseProtos.MetaMessage.Builder.class);
      }

      // Construct using com.docsinclouds.glucose.GlucoseProtos.MetaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contentCase_ = 0;
        content_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.docsinclouds.glucose.GlucoseProtos.internal_static_glucose_MetaMessage_descriptor;
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.MetaMessage getDefaultInstanceForType() {
        return com.docsinclouds.glucose.GlucoseProtos.MetaMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.MetaMessage build() {
        com.docsinclouds.glucose.GlucoseProtos.MetaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.docsinclouds.glucose.GlucoseProtos.MetaMessage buildPartial() {
        com.docsinclouds.glucose.GlucoseProtos.MetaMessage result = new com.docsinclouds.glucose.GlucoseProtos.MetaMessage(this);
        if (contentCase_ == 1) {
          if (sensorValueBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = sensorValueBuilder_.build();
          }
        }
        if (contentCase_ == 2) {
          if (rawBuilder_ == null) {
            result.content_ = content_;
          } else {
            result.content_ = rawBuilder_.build();
          }
        }
        result.contentCase_ = contentCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.docsinclouds.glucose.GlucoseProtos.MetaMessage) {
          return mergeFrom((com.docsinclouds.glucose.GlucoseProtos.MetaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.docsinclouds.glucose.GlucoseProtos.MetaMessage other) {
        if (other == com.docsinclouds.glucose.GlucoseProtos.MetaMessage.getDefaultInstance()) return this;
        switch (other.getContentCase()) {
          case SENSOR_VALUE: {
            mergeSensorValue(other.getSensorValue());
            break;
          }
          case RAW: {
            mergeRaw(other.getRaw());
            break;
          }
          case CONTENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.docsinclouds.glucose.GlucoseProtos.MetaMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.docsinclouds.glucose.GlucoseProtos.MetaMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int contentCase_ = 0;
      private java.lang.Object content_;
      public ContentCase
          getContentCase() {
        return ContentCase.forNumber(
            contentCase_);
      }

      public Builder clearContent() {
        contentCase_ = 0;
        content_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.docsinclouds.glucose.GlucoseProtos.SensorValue, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder, com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> sensorValueBuilder_;
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public boolean hasSensorValue() {
        return contentCase_ == 1;
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue getSensorValue() {
        if (sensorValueBuilder_ == null) {
          if (contentCase_ == 1) {
            return (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_;
          }
          return com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
        } else {
          if (contentCase_ == 1) {
            return sensorValueBuilder_.getMessage();
          }
          return com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
        }
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public Builder setSensorValue(com.docsinclouds.glucose.GlucoseProtos.SensorValue value) {
        if (sensorValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          sensorValueBuilder_.setMessage(value);
        }
        contentCase_ = 1;
        return this;
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public Builder setSensorValue(
          com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder builderForValue) {
        if (sensorValueBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          sensorValueBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 1;
        return this;
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public Builder mergeSensorValue(com.docsinclouds.glucose.GlucoseProtos.SensorValue value) {
        if (sensorValueBuilder_ == null) {
          if (contentCase_ == 1 &&
              content_ != com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance()) {
            content_ = com.docsinclouds.glucose.GlucoseProtos.SensorValue.newBuilder((com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_)
                .mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 1) {
            sensorValueBuilder_.mergeFrom(value);
          }
          sensorValueBuilder_.setMessage(value);
        }
        contentCase_ = 1;
        return this;
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public Builder clearSensorValue() {
        if (sensorValueBuilder_ == null) {
          if (contentCase_ == 1) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 1) {
            contentCase_ = 0;
            content_ = null;
          }
          sensorValueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder getSensorValueBuilder() {
        return getSensorValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder getSensorValueOrBuilder() {
        if ((contentCase_ == 1) && (sensorValueBuilder_ != null)) {
          return sensorValueBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 1) {
            return (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_;
          }
          return com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
        }
      }
      /**
       * <code>.glucose.SensorValue sensor_value = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.docsinclouds.glucose.GlucoseProtos.SensorValue, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder, com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder> 
          getSensorValueFieldBuilder() {
        if (sensorValueBuilder_ == null) {
          if (!(contentCase_ == 1)) {
            content_ = com.docsinclouds.glucose.GlucoseProtos.SensorValue.getDefaultInstance();
          }
          sensorValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.docsinclouds.glucose.GlucoseProtos.SensorValue, com.docsinclouds.glucose.GlucoseProtos.SensorValue.Builder, com.docsinclouds.glucose.GlucoseProtos.SensorValueOrBuilder>(
                  (com.docsinclouds.glucose.GlucoseProtos.SensorValue) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 1;
        onChanged();;
        return sensorValueBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.docsinclouds.glucose.GlucoseProtos.RawValues, com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder, com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder> rawBuilder_;
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public boolean hasRaw() {
        return contentCase_ == 2;
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.RawValues getRaw() {
        if (rawBuilder_ == null) {
          if (contentCase_ == 2) {
            return (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_;
          }
          return com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
        } else {
          if (contentCase_ == 2) {
            return rawBuilder_.getMessage();
          }
          return com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
        }
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public Builder setRaw(com.docsinclouds.glucose.GlucoseProtos.RawValues value) {
        if (rawBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          rawBuilder_.setMessage(value);
        }
        contentCase_ = 2;
        return this;
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public Builder setRaw(
          com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder builderForValue) {
        if (rawBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          rawBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 2;
        return this;
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public Builder mergeRaw(com.docsinclouds.glucose.GlucoseProtos.RawValues value) {
        if (rawBuilder_ == null) {
          if (contentCase_ == 2 &&
              content_ != com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance()) {
            content_ = com.docsinclouds.glucose.GlucoseProtos.RawValues.newBuilder((com.docsinclouds.glucose.GlucoseProtos.RawValues) content_)
                .mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 2) {
            rawBuilder_.mergeFrom(value);
          }
          rawBuilder_.setMessage(value);
        }
        contentCase_ = 2;
        return this;
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public Builder clearRaw() {
        if (rawBuilder_ == null) {
          if (contentCase_ == 2) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 2) {
            contentCase_ = 0;
            content_ = null;
          }
          rawBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder getRawBuilder() {
        return getRawFieldBuilder().getBuilder();
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      public com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder getRawOrBuilder() {
        if ((contentCase_ == 2) && (rawBuilder_ != null)) {
          return rawBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 2) {
            return (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_;
          }
          return com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
        }
      }
      /**
       * <code>.glucose.RawValues raw = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.docsinclouds.glucose.GlucoseProtos.RawValues, com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder, com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder> 
          getRawFieldBuilder() {
        if (rawBuilder_ == null) {
          if (!(contentCase_ == 2)) {
            content_ = com.docsinclouds.glucose.GlucoseProtos.RawValues.getDefaultInstance();
          }
          rawBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.docsinclouds.glucose.GlucoseProtos.RawValues, com.docsinclouds.glucose.GlucoseProtos.RawValues.Builder, com.docsinclouds.glucose.GlucoseProtos.RawValuesOrBuilder>(
                  (com.docsinclouds.glucose.GlucoseProtos.RawValues) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 2;
        onChanged();;
        return rawBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:glucose.MetaMessage)
    }

    // @@protoc_insertion_point(class_scope:glucose.MetaMessage)
    private static final com.docsinclouds.glucose.GlucoseProtos.MetaMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.docsinclouds.glucose.GlucoseProtos.MetaMessage();
    }

    public static com.docsinclouds.glucose.GlucoseProtos.MetaMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MetaMessage>
        PARSER = new com.google.protobuf.AbstractParser<MetaMessage>() {
      @java.lang.Override
      public MetaMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetaMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetaMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetaMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.docsinclouds.glucose.GlucoseProtos.MetaMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glucose_SensorValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glucose_SensorValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glucose_RawValues_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glucose_RawValues_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glucose_MetaMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glucose_MetaMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rglucose.proto\022\007glucose\"D\n\013SensorValue\022" +
      "\r\n\005value\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\t\022\023\n\013sen" +
      "sor_type\030\003 \001(\t\"8\n\tRawValues\022+\n\rsensor_va" +
      "lues\030\001 \003(\0132\024.glucose.SensorValue\"i\n\013Meta" +
      "Message\022,\n\014sensor_value\030\001 \001(\0132\024.glucose." +
      "SensorValueH\000\022!\n\003raw\030\002 \001(\0132\022.glucose.Raw" +
      "ValuesH\000B\t\n\007contentB)\n\030com.docsinclouds." +
      "glucoseB\rGlucoseProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_glucose_SensorValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_glucose_SensorValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glucose_SensorValue_descriptor,
        new java.lang.String[] { "Value", "Timestamp", "SensorType", });
    internal_static_glucose_RawValues_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_glucose_RawValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glucose_RawValues_descriptor,
        new java.lang.String[] { "SensorValues", });
    internal_static_glucose_MetaMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_glucose_MetaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glucose_MetaMessage_descriptor,
        new java.lang.String[] { "SensorValue", "Raw", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
